# Generated by Django 5.1.7 on 2025-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='wikidata_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
