# Generated by Django 5.1.7 on 2025-04-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_graphsnapshot_node_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.space'),
            preserve_default=False,
        ),
    ]
