# Generated by Django 5.1.7 on 2025-10-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='statement_id',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
