# Generated by Django 5.0.7 on 2025-10-26 12:20

from django.db import migrations

def remove_properties_with_null_statement_id(apps, schema_editor):
    """
    Finds and deletes all Property records where statement_id is NULL.
    This cleans up data created before the multi-value property feature.
    """
    Property = apps.get_model('api', 'Property')
    properties_to_delete = Property.objects.filter(statement_id__isnull=True)
    count = properties_to_delete.count()
    if count > 0:
        print(f"\nDeleting {count} old Property records with null statement_id...")
        properties_to_delete.delete()
        print("Deletion complete.")
    else:
        print("\nNo old Property records to delete.")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_property_statement_id'),
    ]

    operations = [
        migrations.RunPython(remove_properties_with_null_statement_id, migrations.RunPython.noop),
    ]
