# Generated by Django 5.1.7 on 2025-10-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_null_statement_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='wikidata_property_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
