# Generated by Django 5.1.7 on 2025-10-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_node_city_node_country_node_district_node_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='statement_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('node', 'statement_id')},
        ),
    ]
