# Generated by Django 5.1.7 on 2025-11-06 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fix_property_statement_id_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('space', 'Space'), ('node', 'Node'), ('discussion', 'Discussion'), ('profile', 'Profile')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('reason', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DISMISSED', 'Dismissed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.space')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='api_report_content_97dd6c_idx'), models.Index(fields=['space'], name='api_report_space_i_590f92_idx'), models.Index(fields=['status'], name='api_report_status_a305b9_idx')],
            },
        ),
    ]