# Generated by Django 5.1.7 on 2025-11-09 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_discussion_is_reported_discussion_report_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
