# Generated by Django 5.1.7 on 2025-11-06 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_node_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
