# Generated by Django 5.1.7 on 2025-11-20 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("space", "Space"),
                            ("node", "Node"),
                            ("profile", "Profile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField()),
                (
                    "archived_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="activity",
            new_name="api_activit_publish_7d0ac6_idx",
            old_name="api_activi_publish_idx",
        ),
        migrations.RenameIndex(
            model_name="activity",
            new_name="api_activit_type_f049ed_idx",
            old_name="api_activi_type_idx",
        ),
        migrations.RenameIndex(
            model_name="activity",
            new_name="api_activit_actor_97e164_idx",
            old_name="api_activi_actor_idx",
        ),
        migrations.RenameIndex(
            model_name="activity",
            new_name="api_activit_object_3e45a7_idx",
            old_name="api_activi_object_idx",
        ),
        migrations.AddField(
            model_name="node",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="space",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="archived_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archives_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(
                fields=["content_type", "content_id"],
                name="api_archive_content_1be283_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(
                fields=["archived_at"], name="api_archive_archive_f685cd_idx"
            ),
        ),
    ]
