# Generated by Django 5.1.7 on 2025-11-20 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def rename_index_if_exists(apps, schema_editor, model_name, old_name, new_name, fields):
    from django.db import connection
    from django.db.utils import ProgrammingError
    
    try:
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE indexname = %s
            """, [old_name])
            
            if cursor.fetchone():
                try:
                    cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
                except ProgrammingError:
                    
                    Model = apps.get_model('api', model_name)
                    index = models.Index(fields=fields, name=new_name)
                    schema_editor.add_index(Model, index)
            else:
               
                Model = apps.get_model('api', model_name)
                index = models.Index(fields=fields, name=new_name)
                try:
                    schema_editor.add_index(Model, index)
                except ProgrammingError:
                   
                    pass
    except Exception:
        
        try:
            Model = apps.get_model('api', model_name)
            index = models.Index(fields=fields, name=new_name)
            schema_editor.add_index(Model, index)
        except Exception:
           
            pass


def reverse_rename_index_if_exists(apps, schema_editor, model_name, old_name, new_name, fields):
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE indexname = %s
        """, [new_name])
        
        if cursor.fetchone():
            cursor.execute(f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"')


class SafeRenameIndex(migrations.RunPython):
    def __init__(self, model_name, old_name, new_name, fields):
        self.model_name = model_name
        self.old_name = old_name
        self.new_name = new_name
        self.fields = fields
        
        super().__init__(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, model_name, old_name, new_name, fields
            ),
            lambda apps, schema_editor: reverse_rename_index_if_exists(
                apps, schema_editor, model_name, old_name, new_name, fields
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("space", "Space"),
                            ("node", "Node"),
                            ("profile", "Profile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField()),
                (
                    "archived_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reason", models.TextField(blank=True, null=True)),
            ],
        ),

        migrations.AddField(
            model_name="node",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="space",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="archived_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archives_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(
                fields=["content_type", "content_id"],
                name="api_archive_content_1be283_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(
                fields=["archived_at"], name="api_archive_archive_f685cd_idx"
            ),
        ),
    ]
