# Generated by Django 5.1.7 on 2025-12-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_edgeproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgeproperty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
