export const API_ENDPOINTS = {
  REGISTER: "/register/",
  LOGIN: "/login/",
  SPACES: "/spaces/",
  TAGS: "/tags/",
  PROFILES: "/profiles/",
  REPORTS: "/reports/",
  REPORTS_OPEN: "/reports/open/",
  REPORTS_DISMISSED: "/reports/dismissed/",
  REPORTS_ARCHIVED: "/reports/archived/",
  REPORTS_REASONS: "/reports/reasons/",
  SEARCH: "/search/",
  TRENDING_SPACES: "/spaces/trending/",
  NODES: (spaceId) => `/spaces/${spaceId}/nodes/`,
  EDGES: (spaceId) => `/spaces/${spaceId}/edges/`,
  SNAPSHOTS: (spaceId) => `/spaces/${spaceId}/snapshots/`,
  DISCUSSIONS: (spaceId) => `/spaces/${spaceId}/discussions/`,
  ADD_DISCUSSION: (spaceId) => `/spaces/${spaceId}/discussions/add/`,
  DISCUSSION_REACT: (spaceId, discussionId) => `/spaces/${spaceId}/discussions/${discussionId}/react/`,
  WIKIDATA_SEARCH: "/spaces/wikidata-search/",
  WIKIDATA_PROPERTY_SEARCH: "/spaces/wikidata-property-search/",
  WIKIDATA_PROPERTIES: (entityId) =>
    `/spaces/wikidata-entity-properties/${entityId}/`,
  PROFILE_ME: "/profiles/me/",
  UPDATE_PROFILE: "/profiles/update_profile/",
  PROFILE: (username) => `/profiles/${username}/user_profile/`,
  ARCHIVE: "/archive/",
  ARCHIVE_CREATE: "/archive/create/",
  ARCHIVE_RESTORE: (archiveId) => `/archive/${archiveId}/restore/`,
  USERS: "/auth/users/",
};

export const GRAPH_CONFIG = {
  NODE_STYLE: {
    width: "80px",
    height: "80px",
    borderRadius: "50%",
    border: "2px solid #1a73e8",
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "10px",
    fontSize: "12px",
    textAlign: "center",
    wordBreak: "break-word",
    lineHeight: "1.2",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  LAYOUT: {
    NODES_PER_ROW: 4,
    NODE_SPACING: 200,
    ROW_SPACING: 200,
    START_X: 200,
    START_Y: 100,
  },
};

export const ERROR_MESSAGES = {
  GRAPH_DATA: "Failed to fetch graph data",
  WIKIDATA_SEARCH: "Failed to search Wikidata",
  ENTITY_PROPERTIES: "Failed to fetch entity properties",
};
