name: Android APK (Debug)

on:
  push:
    branches:
      - "feature/*"     
    paths:
      - "mobile/**"            
  pull_request:
    branches:
      - "feature/*"
    paths:
      - "mobile/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache + wrapper validation
        uses: gradle/actions/setup-gradle@v3

      - name: Build debug APK
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon
        # ":" prefix ensures gradle builds the app module specifically

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: mobile/app/build/outputs/apk/debug/*.apk
