name: feature branch CI

on:
  push:
    branches:
      - "feature/**"

jobs:
  ci:
    uses: SWE574-ConnectTheDots/infra/templates/ci_template.yml@develop
    with:
      run_docker_build: false
      run_compose_tests: true
    secrets: inherit
