name: feature branch CI

on:
  push:
    branches:
      - "feature/**"

jobs:
  ci:
    uses: ../infra/templates/ci_template.yml
    with:
      run_docker_build: false
      run_compose_tests: true
    secrets: inherit
