name: feature branch CI

on:
  push:
    branches:
      - "feature/**"

jobs:
  ci:
    uses: SWE574-Connect-The-Dots/<REPO_NAME>/infra/templates/ci_template.yml@<COMMIT_SHA>
    with:
      run_docker_build: false
      run_compose_tests: true
    secrets: inherit
